version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:3001/api
    volumes:
      - ../frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - JWT_SECRET=dev-secret-key-change-in-production
      - FRONTEND_URL=http://localhost:3000
      - DATABASE_URL=postgresql://warren:warren123@postgres:5432/warren
    volumes:
      - ../backend:/app
      - /app/node_modules
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=warren
      - POSTGRES_USER=warren
      - POSTGRES_PASSWORD=warren123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: